services:
  nginx:
    volumes:
      - ./web/dist:/usr/share/nginx/html/aibase:ro

  bff-service:
    volumes:
      - ./bin/${WANWU_ARCH}/bff-service:/app/bin/bff-service:ro
      - ./configs/microservice/bff-service/configs/config.yaml:/app/configs/microservice/bff-service/configs/config.yaml:ro
      - ./configs/microservice/bff-service/configs/wga/agents/Supervisor/config.yaml:/app/configs/microservice/bff-service/configs/wga/agents/Supervisor/config.yaml:ro

  app-service:
    volumes:
      - ./bin/${WANWU_ARCH}/app-service:/app/bin/app-service:ro

  assistant-service:
    volumes:
      - ./bin/${WANWU_ARCH}/assistant-service:/app/bin/assistant-service:ro

  agent-service:
    volumes:
      - ./bin/${WANWU_ARCH}/agent-service:/app/bin/agent-service:ro

  mcp-service:
    volumes:
      - ./bin/${WANWU_ARCH}/mcp-service:/app/bin/mcp-service:ro
    environment:
      SERVER_API_BASE_URL: http://bff-service:6667
