export const overviewStats = [
  { key: 'todayNew', value: 328, change: '+12.6%', compare: 'yesterday' },
  { key: 'hotEvents', value: 12, change: '+2', compare: 'yesterday' },
  { key: 'risksToWatch', value: 4, change: '-1', compare: 'yesterday' },
  { key: 'studentConcerns', value: 18, change: '+3', compare: 'lastWeek' },
];

export const trendData = {
  dates: ['08-07', '08-08', '08-09', '08-10', '08-11', '08-12', '08-13'],
  total: [196, 224, 218, 276, 251, 294, 328],
  negative: [32, 38, 41, 56, 49, 63, 72],
};

export const sentimentData = [
  { key: 'positive', value: 52 },
  { key: 'neutral', value: 30 },
  { key: 'negative', value: 18 },
];

export const hotTopics = [
  { name: '宿舍维修', heat: 986, change: '+36%' },
  { name: '选课系统', heat: 842, change: '+28%' },
  { name: '食堂服务', heat: 735, change: '+15%' },
  { name: '校园网络', heat: 681, change: '+22%' },
  { name: '就业招聘', heat: 596, change: '+9%' },
];

export const riskEvents = [
  { name: '新区宿舍维修问题', heat: 892, risk: 'high' },
  { name: '校园网络阶段性异常', heat: 764, risk: 'high' },
  { name: '选课系统访问拥堵', heat: 703, risk: 'normal' },
  { name: '部分食堂窗口价格讨论', heat: 618, risk: 'normal' },
  { name: '就业招聘信息真实性讨论', heat: 557, risk: 'normal' },
];

export const concernTopics = [
  {
    name: '宿舍维修',
    discussions: 428,
    weeklyChange: '+36%',
    sentiment: 'negative',
    serviceArea: '后勤服务',
    needs: ['希望缩短维修响应时间', '希望公布维修进度', '希望加强夜间维修保障'],
  },
  {
    name: '食堂服务',
    discussions: 356,
    weeklyChange: '+15%',
    sentiment: 'neutral',
    serviceArea: '餐饮服务',
    needs: [
      '希望丰富平价菜品',
      '希望优化高峰期排队秩序',
      '希望及时公示窗口信息',
    ],
  },
  {
    name: '选课系统',
    discussions: 314,
    weeklyChange: '+28%',
    sentiment: 'negative',
    serviceArea: '教学服务',
    needs: ['希望提高高峰期系统稳定性', '希望明确课程余量', '希望完善冲突提示'],
  },
  {
    name: '校园网络',
    discussions: 286,
    weeklyChange: '+22%',
    sentiment: 'negative',
    serviceArea: '信息服务',
    needs: ['希望改善晚间网络质量', '希望及时发布故障进展', '希望简化报修流程'],
  },
  {
    name: '奖助学金',
    discussions: 193,
    weeklyChange: '+8%',
    sentiment: 'neutral',
    serviceArea: '学生服务',
    needs: ['希望集中发布申报时间', '希望明确材料要求', '希望提供进度查询入口'],
  },
  {
    name: '就业升学',
    discussions: 267,
    weeklyChange: '+12%',
    sentiment: 'positive',
    serviceArea: '发展服务',
    needs: [
      '希望增加校内招聘场次',
      '希望加强岗位信息核验',
      '希望提供分专业指导',
    ],
  },
];

export const alerts = [
  {
    id: 'alert-01',
    name: '新区宿舍维修问题',
    risk: 'high',
    heat: 892,
    growth24h: '+86%',
    negativeRatio: '74%',
    reason: '讨论量短期增长明显，且诉求集中于维修响应和信息公开。',
    status: '持续升温',
    updatedAt: '2026-08-13 14:20',
  },
  {
    id: 'alert-02',
    name: '校园网络阶段性异常',
    risk: 'high',
    heat: 764,
    growth24h: '+61%',
    negativeRatio: '68%',
    reason: '晚间网络体验相关讨论集中出现，学生期待明确故障恢复时间。',
    status: '持续关注',
    updatedAt: '2026-08-13 13:48',
  },
  {
    id: 'alert-03',
    name: '选课系统访问拥堵',
    risk: 'normal',
    heat: 703,
    growth24h: '+43%',
    negativeRatio: '57%',
    reason: '讨论集中在选课开放时段，当前热度增速已逐步放缓。',
    status: '热度回落',
    updatedAt: '2026-08-13 12:35',
  },
  {
    id: 'alert-04',
    name: '部分食堂窗口价格讨论',
    risk: 'normal',
    heat: 618,
    growth24h: '+29%',
    negativeRatio: '51%',
    reason: '学生关注价格公示和菜品分量，相关表达较为集中。',
    status: '平稳跟踪',
    updatedAt: '2026-08-13 11:10',
  },
  {
    id: 'alert-05',
    name: '就业招聘信息真实性讨论',
    risk: 'low',
    heat: 557,
    growth24h: '+12%',
    negativeRatio: '34%',
    reason: '少量公开讨论希望加强企业资质和岗位内容核验。',
    status: '常规关注',
    updatedAt: '2026-08-13 09:42',
  },
];

export const opinionList = [
  {
    id: 1,
    title: '同学们关注新区宿舍维修进度',
    source: '校园服务反馈',
    publishedAt: '2026-08-13 14:12',
    topic: '宿舍维修',
    sentiment: 'negative',
    risk: 'high',
    heat: 892,
    status: '持续升温',
  },
  {
    id: 2,
    title: '晚间校园网络使用体验讨论增多',
    source: '公开论坛',
    publishedAt: '2026-08-13 13:36',
    topic: '校园网络',
    sentiment: 'negative',
    risk: 'high',
    heat: 764,
    status: '持续关注',
  },
  {
    id: 3,
    title: '新学期选课开放时间与操作提示发布',
    source: '校园新闻网',
    publishedAt: '2026-08-13 12:50',
    topic: '选课系统',
    sentiment: 'neutral',
    risk: 'normal',
    heat: 703,
    status: '热度回落',
  },
  {
    id: 4,
    title: '食堂平价菜品供应受到公开讨论',
    source: '公开评论区',
    publishedAt: '2026-08-13 11:25',
    topic: '食堂服务',
    sentiment: 'neutral',
    risk: 'normal',
    heat: 618,
    status: '平稳跟踪',
  },
  {
    id: 5,
    title: '秋季校园招聘活动安排引发关注',
    source: '公开社交平台',
    publishedAt: '2026-08-13 10:18',
    topic: '就业升学',
    sentiment: 'positive',
    risk: 'low',
    heat: 596,
    status: '常规关注',
  },
  {
    id: 6,
    title: '奖助学金申报材料说明获得转发',
    source: '校园新闻网',
    publishedAt: '2026-08-12 18:42',
    topic: '奖助学金',
    sentiment: 'neutral',
    risk: 'low',
    heat: 431,
    status: '信息传播',
  },
  {
    id: 7,
    title: '学生建议延长图书馆部分区域开放时间',
    source: '校园服务反馈',
    publishedAt: '2026-08-12 16:34',
    topic: '学习空间',
    sentiment: 'neutral',
    risk: 'low',
    heat: 386,
    status: '诉求汇总',
  },
  {
    id: 8,
    title: '校园体育场地预约规则受到关注',
    source: '公开论坛',
    publishedAt: '2026-08-12 14:06',
    topic: '校园设施',
    sentiment: 'neutral',
    risk: 'low',
    heat: 352,
    status: '平稳跟踪',
  },
  {
    id: 9,
    title: '迎新志愿服务获得积极评价',
    source: '公开社交平台',
    publishedAt: '2026-08-12 11:20',
    topic: '校园活动',
    sentiment: 'positive',
    risk: 'low',
    heat: 335,
    status: '正向传播',
  },
  {
    id: 10,
    title: '部分宿舍楼热水供应时间讨论',
    source: '公开评论区',
    publishedAt: '2026-08-11 20:15',
    topic: '宿舍维修',
    sentiment: 'negative',
    risk: 'normal',
    heat: 524,
    status: '持续关注',
  },
  {
    id: 11,
    title: '学生关注食堂高峰期排队秩序',
    source: '校园服务反馈',
    publishedAt: '2026-08-11 17:48',
    topic: '食堂服务',
    sentiment: 'negative',
    risk: 'normal',
    heat: 487,
    status: '诉求汇总',
  },
  {
    id: 12,
    title: '校内招聘岗位信息核验建议',
    source: '公开论坛',
    publishedAt: '2026-08-11 15:32',
    topic: '就业升学',
    sentiment: 'neutral',
    risk: 'normal',
    heat: 557,
    status: '持续关注',
  },
  {
    id: 13,
    title: '校园网故障报修流程公开说明',
    source: '校园新闻网',
    publishedAt: '2026-08-10 19:16',
    topic: '校园网络',
    sentiment: 'positive',
    risk: 'low',
    heat: 298,
    status: '回应跟踪',
  },
  {
    id: 14,
    title: '选修课程余量信息展示建议',
    source: '校园服务反馈',
    publishedAt: '2026-08-10 16:08',
    topic: '选课系统',
    sentiment: 'neutral',
    risk: 'normal',
    heat: 463,
    status: '诉求汇总',
  },
  {
    id: 15,
    title: '奖助学金申请进度查询受到关注',
    source: '公开评论区',
    publishedAt: '2026-08-09 13:44',
    topic: '奖助学金',
    sentiment: 'neutral',
    risk: 'low',
    heat: 276,
    status: '平稳跟踪',
  },
  {
    id: 16,
    title: '校园文化活动报名反响积极',
    source: '公开社交平台',
    publishedAt: '2026-08-09 10:27',
    topic: '校园活动',
    sentiment: 'positive',
    risk: 'low',
    heat: 319,
    status: '正向传播',
  },
  {
    id: 17,
    title: '教学楼自习区域照明改善建议',
    source: '校园服务反馈',
    publishedAt: '2026-08-08 19:03',
    topic: '校园设施',
    sentiment: 'neutral',
    risk: 'low',
    heat: 241,
    status: '诉求汇总',
  },
  {
    id: 18,
    title: '就业指导讲座内容获得公开好评',
    source: '校园新闻网',
    publishedAt: '2026-08-07 15:21',
    topic: '就业升学',
    sentiment: 'positive',
    risk: 'low',
    heat: 224,
    status: '正向传播',
  },
];

export const reports = [
  {
    id: 'report-01',
    name: '校园舆情日报（演示）',
    type: '舆情日报',
    generatedAt: '2026-08-13 09:00',
    status: '已生成',
  },
  {
    id: 'report-02',
    name: '校园舆情周报（演示）',
    type: '舆情周报',
    generatedAt: '2026-08-11 09:00',
    status: '已生成',
  },
  {
    id: 'report-03',
    name: '校园服务热点专题报告（演示）',
    type: '专题报告',
    generatedAt: '2026-08-12 16:30',
    status: '草稿',
  },
  {
    id: 'report-04',
    name: '新区宿舍维修事件研判报告（演示）',
    type: '事件研判报告',
    generatedAt: '2026-08-13 14:30',
    status: '待生成',
  },
];
